[font]
size = 9
#9
#13

[font.bold]
family = "UbuntuMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "UbuntuMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "UbuntuMonoNerdFont"
style = "Italic"

[font.normal]
family = "UbuntuMonoNerdFont"
style = "Bold"

# Alacritty's default color scheme pre-0.13 (based on tomorrow_night)
# https://github.com/alacritty/alacritty/blob/v0.12.3/alacritty/src/config/color.rs

# [colors.primary]
# foreground = "#c5c8c6"
# background = "#1d1f21"
#
# [colors.normal]
# black = "#1d1f21"
# red = "#cc6666"
# green = "#b5bd68"
# yellow = "#f0c674"
# blue = "#81a2be"
# magenta = "#b294bb"
# cyan = "#8abeb7"
# white = "#c5c8c6"
#
# [colors.bright]
# black = "#666666"
# red = "#d54e53"
# green = "#b9ca4a"
# yellow = "#e7c547"
# blue = "#7aa6da"
# magenta = "#c397d8"
# cyan = "#70c0b1"
# white = "#eaeaea"
#
# [colors.dim]
# black = "#131415"
# red = "#864343"
# green = "#777c44"
# yellow = "#9e824c"
# blue = "#556a7d"
# magenta = "#75617b"
# cyan = "#5b7d78"


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
