#!/bin/dash

COMMAND="$(ps -e | grep 'bluetoothd' | tail -c2)"

case "$COMMAND" in
    "d") printf "  $(bluetoothctl info | grep Name: | sed 's/^[[:space:]]*//g' | sed -e "s/ //g" | sed 's/Name://g')" ;;
    *) 
        printf "" ;;
esac
