#!/bin/dash

COMMAND="$(pactl list | sed -n '/^Source/,/^$/p' | grep Mute | grep yes | tail -c2)"

case "$COMMAND" in
 "s") printf "$(pactl list | sed -n '/^Source/,/^$/p' | grep yes | wc -l)  " ;;
  *) printf " " ;;
esac
