#!/bin/dash

wlan() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "^c$black^ ^b$green^ 󰤨  ^d^%s" " ^c$green^$(iwctl station wlp4s0 show | grep "Connected network" | awk '{print $NF}')" ;;
	down) printf "^c$black^ ^b$red^ 󰤭  ^d^%s" " ^c$red^Disconnected" ;;
	esac
}
