#!/bin/sh
# changeVolume
# msgTag="volumechange"

volume="$(pamixer --get-volume)"

# Show the volume notification
notify-send -a "changeVolume" -h string:x-dunst-stack-tag:$msgTag -i $iconPath/audio-volume-high.png -h int:value:"$volume" "Volume: ${volume}" --expire-time=1000

